# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(732, 604)
        self.gridLayout = QtWidgets.QGridLayout(Widget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_close = QtWidgets.QPushButton(Widget)
        self.pushButton_close.setObjectName("pushButton_close")
        self.gridLayout.addWidget(self.pushButton_close, 3, 1, 1, 1)
        self.pushButton_search = QtWidgets.QPushButton(Widget)
        self.pushButton_search.setObjectName("pushButton_search")
        self.gridLayout.addWidget(self.pushButton_search, 2, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(Widget)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 4, 0, 1, 2)
        self.lineEdit_song = QtWidgets.QLineEdit(Widget)
        self.lineEdit_song.setObjectName("lineEdit_song")
        self.gridLayout.addWidget(self.lineEdit_song, 0, 0, 1, 2)
        self.pushButton_crawler = QtWidgets.QPushButton(Widget)
        self.pushButton_crawler.setObjectName("pushButton_crawler")
        self.gridLayout.addWidget(self.pushButton_crawler, 2, 1, 1, 1)
        self.pushButton_mp3dir = QtWidgets.QPushButton(Widget)
        self.pushButton_mp3dir.setObjectName("pushButton_mp3dir")
        self.gridLayout.addWidget(self.pushButton_mp3dir, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(Widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 0, 1, 2)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.pushButton_close.setText(_translate("Widget", "关闭窗口"))
        self.pushButton_search.setText(_translate("Widget", "搜索"))
        self.lineEdit_song.setPlaceholderText(_translate("Widget", "搜索歌曲"))
        self.pushButton_crawler.setText(_translate("Widget", "爬取歌曲"))
        self.pushButton_mp3dir.setText(_translate("Widget", "MP3目录"))
        self.label.setText(_translate("Widget", "状态"))
